### ISSUE TITLE
ipython is not in the package dependencies

### ISSUE THREAD

**Issue by ccossou** [droyed/benchit#3]
I just did:
pip install benchit

When I tried to use it, I got the error:
```
Traceback (most recent call last):
  File "/local/home/ccossou/.config/JetBrains/PyCharmCE2021.1/scratches/scratch_14.py", line 29, in <module>
    t = benchit.timings(funcs, in_)
  File "/local/home/ccossou/virtualenv/sandbox/lib/python3.8/site-packages/benchit/main.py", line 456, in timings
    t_ = _get_timings(funcs, inputs_p, multivar=multivar)
  File "/local/home/ccossou/virtualenv/sandbox/lib/python3.8/site-packages/benchit/main.py", line 240, in _get_timings
    timings[i, :] = _get_timings_perinput(funcs, input_)
  File "/local/home/ccossou/virtualenv/sandbox/lib/python3.8/site-packages/benchit/main.py", line 179, in _get_timings_perinput
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
```

I got the example code from this example:
https://stackoverflow.com/a/48240995

When I did:
```bash
pip install ipython
```
it solved the problem.

Hope it helps,

**Comment by droyed** [comment]
@ccossou Thank you! New commits on it.
